name: Python unittest
permissions: write-all

on:
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instal Pytest
      run: |
         python -m pip install --upgrade pip
         pip install -U pytest
         pytest --version    
    - name: Test with pytest
      run: pytest -rp calculator_pytest.py > Pytests${{github.run_number}}.txt
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
      
      
  unittest:
    needs: [pytest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test with unittest
      run: python -m unittest -v calculator_unittest.py > Unittests${{github.run_number}}.txt
    - name: Commit files
      run: |
        git config --local user.email "kovak5063@gmail.com"
        git config --local user.name "OvakK"
        git add Unittests${{github.run_number}}.txt
        git commit -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force_with_lease: true
      
  run_calculator:
    needs: [ unittest, pytest ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run calculator
      run: python calculator.py
      
      
