name: Python unittest

on:
  workflow_dispatch:
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test with unittest
      run: python -m unittest -v calculator_unittest.py
        
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: ctions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        pythom-version: "3.10"
    - name: Test with pytest
      run: pytest -rp calculator_pytest.py
