name: Tests2
permissions: write-all


on:
  workflow_dispatch:
    inputs:
      EXPRESSION:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  tests:
    strategy:
      matrix:
        python-versions: [3.8.14, 3.9.0, 3.10] 
        os-versions: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os-versions }}
    steps:
    - name: Print expression
      run: echo ${{ env.EXPRESSION }}
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-versions }}
    - name: Instal Pytest
      run: |
         python -m pip install --upgrade pip
         pip install -U pytest
         pytest --version    
    - name: Test with pytest
      run: pytest -rp calculator_pytest.py > Pytests${{github.run_number}}.txt
    - name: Test with unittest
      run: python -m unittest -v calculator_unittest.py > Unittests${{github.run_number}}.txt
    - name: Commit files
      run: |
        git config --local user.email "kovak5063@gmail.com"
        git config --local user.name "OvakK"
        git add Pytests${{github.run_number}}.txt Unittest_results.txt
        git commit -m "Tests ${{github.run_number}}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      
      
  run_calculator:
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run calculator
      run: python calculator.py
