name: Python unittest
permissions: write-all

on:
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instal Pytest
      run: |
         python -m pip install --upgrade pip
         pip install -U pytest
         pytest --version    
    - name: Test with pytest
      run: pytest -rp calculator_pytest.py > Pytests${{github.run_number}}.txt
      
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test with unittest
      run: python -m unittest -v calculator_unittest.py > Unittests${{github.run_number}}.txt
    - name: Change test results
      run: |
       git config --global user.name "OvakK"
       git config --global user.email "kovak5063@gmail.com"
       git add Unittests${{github.run_number}}.txt
       git commit -m "Test number ${{github.run_number}}"
       git push
      
  run_calculator:
    needs: [ unittest, pytest ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run calculator
      run: python calculator.py
      
      
